# use the gcc c compiler
CC = gcc

# use the gcc cpp compiler
CPP = g++

# flags
SDL_FLAGS = $(shell sdl-config --cflags --libs) -lSDL_image

# show all warnings
CPPFLAGS =-Wall -Wextra -pedantic -lGL -lGLU $(SDL_FLAGS) 

# show all warnings
CFLAGS =-Wall -Wextra -pedantic

VERSION_MAJOR = 0
VERSION_MINOR = 1

